# configuration file for sourcery.ai
# config reference: https://docs.sourcery.ai/Reference/Configuration/sourcery-yaml/#github

version: '1'  # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
- .git
- venv
- .venv
- env
- .env
- .tox
- config.ini

rule_settings:
  enable:
  - default
  disable: []  # A list of rule IDs Sourcery will never suggest.
  rule_types:
  - refactoring
  - suggestion
  - comment
  python_version: '3.11' # A string specifying the lowest Python version your project supports. Sourcery will not suggest refactorings requiring a higher Python version.

github:
  ignore_labels:
  - sourcery-ignore
  - documentation
  - wontfix
  request_review:
      origin: owner
      forked: author
  sourcery_branch: sourcery/{base_branch}
